sudo: required
env:
  - SH=dash
  - SH=bash
before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install rng-tools
# see https://github.com/travis-ci/travis-ci/issues/1913#issuecomment-53972361
  - sudo rm -f /dev/random
  - sudo mknod -m 0666 /dev/random c 1 9
  - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
  - sudo /etc/init.d/rng-tools restart
script:
  - find bin lib -type f | xargs shellcheck -s sh
  - make check
notifications:
  irc: "chat.freenode.net#freight"
